// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRhrOlaEf8GKEY2MVIrfi4J5C4j-VS8lQ',
    appId: '1:1003556409130:android:ee7d37c59e0ac99e73d853',
    messagingSenderId: '1003556409130',
    projectId: 'we-chat-9ede7',
    storageBucket: 'we-chat-9ede7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS1-nU11c2NE4-nDowirQo5_dCooFHD8w',
    appId: '1:1003556409130:ios:9b452f6f1a84c16673d853',
    messagingSenderId: '1003556409130',
    projectId: 'we-chat-9ede7',
    storageBucket: 'we-chat-9ede7.appspot.com',
    androidClientId: '1003556409130-jm3kc5cd1iog0jde7h7q2qk5psmbvhe9.apps.googleusercontent.com',
    iosClientId: '1003556409130-6btrrsbk3j8lhk88e3698ktg7jgjevpp.apps.googleusercontent.com',
    iosBundleId: 'com.example.weChat',
  );
}
